pop-up window
Abenezer-Tilahun/Microverse-Portfolio-Website pull request #12
Opened 2022-02-01 12:58 UTC by Abenezer-Tilahun

2022-02-01 15:11 UTC, Hamzaoutdoors requested changes
Hey team, I am **Hamza** your reviewer for this PR 😸 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## To Highlight
✔️ The repo looks professional
✔️ Git/GitHub flow best practices have been followed
✔️ There are no linter errors
✔️ You have a descriptive README
✔️ The Popup behaviors working as expected

## Required Changes ♻️

_See the inline comments below for more required changes 😃_  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- Kindly try to change the `JS` file name because as convention the js files should be in lowercase,

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-01 15:11 UTC, Hamzaoutdoors commented on index.html
> +            </ul>
- [x] All this part inside the `div` with id `popup` should be created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code -  Kindly work on this

2022-02-01 15:11 UTC, Hamzaoutdoors commented on Script.js
> +// Popup Window start////////////////////
- [x]  I am inviting you to remove all the commented code from the `Script.js` file as it would be recommended to not push the commented code as it makes the codebase little messy and unclear. and the code should be self explanatory

2022-02-02 09:27 UTC, ShoiraTa requested changes
Hi team,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

- [ ] Currently the JS file is crushing, because in index JS you have mistyped the JS file name:

![image](https://user-images.githubusercontent.com/77038610/152126766-606262b8-bfd1-4dcd-9c6b-8488680f435c.png)
Please  change it to    ` <script src="./Script.js"></script>` to make the app work

- [x] OPTIONAL: I strongly recommend you to meet Figma design, currently the buttons are different:

Figma  | Yours
------------- | -------------
![image](https://user-images.githubusercontent.com/77038610/152127312-07f24d89-fe16-4523-bbd1-0e5fd02fbea7.png)l  | ![image](https://user-images.githubusercontent.com/77038610/152127116-38f0426f-32d1-44f8-accf-4d67fe45b911.png)

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 09:45 UTC, Meltrust approved these changes
Hi @Abenezer-Tilahun, 

## Thanks for implementing the previous reviewer's requirements!! 🎖️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 10:07 UTC, merged

2022-04-09 19:13 UTC, Abenezer-Tilahun commented on index.html
> +            </ul>
Ok I will create popup window inside div dynamically.

2022-04-09 19:13 UTC, Abenezer-Tilahun commented on Script.js
> +// Popup Window start////////////////////
Ok I will remove the commented code.